### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by rugk** [micahflee/torbrowser-launcher#407]
It would be great if you could provide a flatpak package of this app, e.g. to https://flathub.org/.

Flatpaks can of course be installed on any distro and are easy to update. See https://flatpak.org/

I know that at least Firefox (pre-releases) are available as a flatpak: https://firefox-flatpak.mojefedora.cz/
Maybe that should make it easier for you to implement this, because you can have a look on how they do it.

Also asked downstream, because they have their own packaging infrastructure for flatpaks, but received no reply yet: https://bugzilla.redhat.com/show_bug.cgi?id=1731284 (I also guess a version on Flathub would be more prominent.)

Also asked the "somewhat" upstream, i.e. Tor Browser directly, but they do not seem to have any plans yet: https://trac.torproject.org/projects/tor/ticket/25578

Related discussion: https://discussion.fedoraproject.org/t/tor-browser-on-silverblue/2032?u=rugk

**Comment by rugk** [comment]
Oh, did not notice that, but actually there is already a proposed Flatpak manifest for Tor Browser (Lauchner): https://trac.torproject.org/projects/tor/ticket/25578#comment:8

Maybe this can be more officially supported/maintained (AFAIK they've asked for a maintainer there).

**Comment by AsciiWolf** [comment]
I started working on this as well. This is what I have at this moment:

```
app-id: com.github.micahflee.torbrowser-launcher
runtime: org.gnome.Platform
runtime-version: '3.32'
sdk: org.gnome.Sdk
separate-locales: false
command: torbrowser-launcher
rename-desktop-file: torbrowser.desktop
rename-appdata-file: torbrowser.appdata.xml
rename-icon: torbrowser
finish-args:
  - --share=ipc
  - --share=network
  - --socket=x11
  - --socket=pulseaudio
modules:
  - name: torbrowser-launcher
    buildsystem: simple
    sources:
        - type: archive
          url: https://github.com/micahflee/torbrowser-launcher/archive/v0.3.2.tar.gz
          sha256: 25ad4b0c70579628bf18f4cdcd18ac303fe4f7f1c590cc48df2a87651c92991c
    build-commands:
        - "python3 setup.py install --prefix=/app --root=/ --optimize=1"
    post-install:
        - "sed -i 's:Icon=torbrowser:Icon=com.github.micahflee.torbrowser-launcher:' /app/share/applications/torbrowser-settings.desktop"
        - "mv /app/share/applications/torbrowser-settings.desktop /app/share/applications/com.github.micahflee.torbrowser-launcher.settings.desktop"
```

Unfortunately, it does not work because of #413.
